# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Vbox\VboxCenter\forms\setting_form.ui'
#
# Created: Mon Apr 13 17:01:22 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_setting_form(object):
    def setupUi(self, setting_form):
        setting_form.setObjectName(_fromUtf8("setting_form"))
        setting_form.resize(713, 488)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(setting_form.sizePolicy().hasHeightForWidth())
        setting_form.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(setting_form)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.le_vmname = QtGui.QLineEdit(self.centralwidget)
        self.le_vmname.setGeometry(QtCore.QRect(120, 30, 141, 21))
        self.le_vmname.setObjectName(_fromUtf8("le_vmname"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cb_vmOS = QtGui.QComboBox(self.centralwidget)
        self.cb_vmOS.setGeometry(QtCore.QRect(120, 70, 141, 22))
        self.cb_vmOS.setObjectName(_fromUtf8("cb_vmOS"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.sb_cpucount = QtGui.QSpinBox(self.centralwidget)
        self.sb_cpucount.setGeometry(QtCore.QRect(150, 100, 42, 22))
        self.sb_cpucount.setMinimum(1)
        self.sb_cpucount.setProperty("value", 1)
        self.sb_cpucount.setObjectName(_fromUtf8("sb_cpucount"))
        self.sb_cpuexecutioncap = QtGui.QSpinBox(self.centralwidget)
        self.sb_cpuexecutioncap.setGeometry(QtCore.QRect(150, 130, 42, 22))
        self.sb_cpuexecutioncap.setMinimum(40)
        self.sb_cpuexecutioncap.setMaximum(100)
        self.sb_cpuexecutioncap.setProperty("value", 100)
        self.sb_cpuexecutioncap.setObjectName(_fromUtf8("sb_cpuexecutioncap"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sb_vmvmemsize = QtGui.QSpinBox(self.centralwidget)
        self.sb_vmvmemsize.setGeometry(QtCore.QRect(140, 190, 41, 22))
        self.sb_vmvmemsize.setMinimum(18)
        self.sb_vmvmemsize.setProperty("value", 21)
        self.sb_vmvmemsize.setObjectName(_fromUtf8("sb_vmvmemsize"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 190, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 160, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.te=QtGui.QPlainTextEdit(self.centralwidget)
        self.te.setGeometry(QtCore.QRect(40, 290, 256, 131))
        self.te.setObjectName(_fromUtf8("te"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 160, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lab_vmdiskname = QtGui.QLabel(self.centralwidget)
        self.lab_vmdiskname.setGeometry(QtCore.QRect(390, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmdiskname.setFont(font)
        self.lab_vmdiskname.setObjectName(_fromUtf8("lab_vmdiskname"))
        self.btn_opendir = QtGui.QPushButton(self.centralwidget)
        self.btn_opendir.setGeometry(QtCore.QRect(630, 160, 41, 23))
        self.btn_opendir.setObjectName(_fromUtf8("btn_opendir"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 190, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.wg_NA = QtGui.QWidget(self.centralwidget)
        self.wg_NA.setGeometry(QtCore.QRect(310, 230, 351, 191))
        self.wg_NA.setObjectName(_fromUtf8("wg_NA"))
        self.label_12 = QtGui.QLabel(self.wg_NA)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cb_NAattachmentType = QtGui.QComboBox(self.wg_NA)
        self.cb_NAattachmentType.setEnabled(False)
        self.cb_NAattachmentType.setGeometry(QtCore.QRect(70, 10, 271, 22))
        self.cb_NAattachmentType.setObjectName(_fromUtf8("cb_NAattachmentType"))
        self.label_13 = QtGui.QLabel(self.wg_NA)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cb_NAbridgedinterface = QtGui.QComboBox(self.wg_NA)
        self.cb_NAbridgedinterface.setEnabled(True)
        self.cb_NAbridgedinterface.setGeometry(QtCore.QRect(70, 50, 271, 22))
        self.cb_NAbridgedinterface.setEditable(False)
        self.cb_NAbridgedinterface.setObjectName(_fromUtf8("cb_NAbridgedinterface"))
        self.cb_NAadaptertype = QtGui.QComboBox(self.wg_NA)
        self.cb_NAadaptertype.setEnabled(True)
        self.cb_NAadaptertype.setGeometry(QtCore.QRect(70, 90, 271, 22))
        self.cb_NAadaptertype.setEditable(False)
        self.cb_NAadaptertype.setObjectName(_fromUtf8("cb_NAadaptertype"))
        self.label_14 = QtGui.QLabel(self.wg_NA)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.wg_NA)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.le_MACaddress = QtGui.QLineEdit(self.wg_NA)
        self.le_MACaddress.setGeometry(QtCore.QRect(80, 130, 121, 20))
        self.le_MACaddress.setMaxLength(12)
        self.le_MACaddress.setObjectName(_fromUtf8("le_MACaddress"))
        self.btn_MACgenerator = QtGui.QPushButton(self.wg_NA)
        self.btn_MACgenerator.setGeometry(QtCore.QRect(210, 130, 75, 23))
        self.btn_MACgenerator.setObjectName(_fromUtf8("btn_MACgenerator"))
        self.cheakb_cableconnected = QtGui.QCheckBox(self.wg_NA)
        self.cheakb_cableconnected.setGeometry(QtCore.QRect(10, 160, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.cheakb_cableconnected.setFont(font)
        self.cheakb_cableconnected.setObjectName(_fromUtf8("cheakb_cableconnected"))
        self.cheakb_NAenabled = QtGui.QCheckBox(self.centralwidget)
        self.cheakb_NAenabled.setGeometry(QtCore.QRect(390, 190, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.cheakb_NAenabled.setFont(font)
        self.cheakb_NAenabled.setAcceptDrops(False)
        self.cheakb_NAenabled.setChecked(False)
        self.cheakb_NAenabled.setObjectName(_fromUtf8("cheakb_NAenabled"))
        self.tab_bootorder = QtGui.QTableWidget(self.centralwidget)
        self.tab_bootorder.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tab_bootorder.setGeometry(QtCore.QRect(370, 40, 71, 111))
        self.tab_bootorder.setObjectName(_fromUtf8("tab_bootorder"))
        self.tab_bootorder.setColumnCount(1)
        self.tab_bootorder.setRowCount(4)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(310, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.btn_up = QtGui.QPushButton(self.centralwidget)
        self.btn_up.setGeometry(QtCore.QRect(460, 50, 75, 23))
        self.btn_up.setObjectName(_fromUtf8("btn_up"))
        self.btn_down = QtGui.QPushButton(self.centralwidget)
        self.btn_down.setGeometry(QtCore.QRect(460, 110, 75, 23))
        self.btn_down.setObjectName(_fromUtf8("btn_down"))
        self.btn_confirm = QtGui.QPushButton(self.centralwidget)
        self.btn_confirm.setGeometry(QtCore.QRect(240, 430, 81, 31))
        self.btn_confirm.setObjectName(_fromUtf8("btn_confirm"))
        self.btn_cancel = QtGui.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(380, 430, 81, 31))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.sb_vmmemsize = QtGui.QSpinBox(self.centralwidget)
        self.sb_vmmemsize.setGeometry(QtCore.QRect(130, 160, 51, 22))
        self.sb_vmmemsize.setMinimum(128)
        self.sb_vmmemsize.setMaximum(8064)
        self.sb_vmmemsize.setProperty("value", 256)
        self.sb_vmmemsize.setObjectName(_fromUtf8("sb_vmmemsize"))
        setting_form.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(setting_form)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        setting_form.setStatusBar(self.statusbar)

        self.retranslateUi(setting_form)
        QtCore.QMetaObject.connectSlotsByName(setting_form)
        QtCore.QObject.connect(self.btn_MACgenerator,QtCore.SIGNAL(_fromUtf8('clicked()')),setting_form.MACGenerator)
        QtCore.QObject.connect(self.btn_up,QtCore.SIGNAL(_fromUtf8('clicked()')),setting_form.bootorder_up)
        QtCore.QObject.connect(self.btn_down,QtCore.SIGNAL(_fromUtf8('clicked()')),setting_form.bootorder_down)
        QtCore.QObject.connect(self.btn_cancel,QtCore.SIGNAL(_fromUtf8("clicked()")),setting_form.close)
        QtCore.QObject.connect(self.cheakb_NAenabled, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), setting_form.setNAwidgetEnabled)
        QtCore.QObject.connect(self.btn_opendir,QtCore.SIGNAL(_fromUtf8("clicked()")),setting_form.openFileselectDialog)

    def retranslateUi(self, setting_form):
        setting_form.setWindowTitle(_translate("setting_form", "虚拟机设定", None))
        self.label.setText(_translate("setting_form", "虚拟机名称:", None))
        self.label_2.setText(_translate("setting_form", "虚拟机系统:", None))
        self.label_3.setText(_translate("setting_form", "处理器数量分配:", None))
        self.label_4.setText(_translate("setting_form", "处理器使用峰值:", None))
        self.label_5.setText(_translate("setting_form", "内存大小:", None))
        self.label_6.setText(_translate("setting_form", "显存大小:", None))
        self.label_7.setText(_translate("setting_form", "MB", None))
        self.label_9.setText(_translate("setting_form", "MB", None))
        self.label_8.setText(_translate("setting_form", "虚拟机描述:", None))
        self.label_10.setText(_translate("setting_form", "虚拟机光驱:", None))
        self.lab_vmdiskname.setText(_translate("setting_form", "diskname", None))
        self.btn_opendir.setText(_translate("setting_form", "...", None))
        self.label_11.setText(_translate("setting_form", "网络适配器:", None))
        self.label_12.setText(_translate("setting_form", "连接方式:", None))
        self.label_13.setText(_translate("setting_form", "接口名称:", None))
        self.label_14.setText(_translate("setting_form", "控制芯片:", None))
        self.label_15.setText(_translate("setting_form", "MAC地址:", None))
        self.btn_MACgenerator.setText(_translate("setting_form", "随机生成", None))
        self.cheakb_cableconnected.setText(_translate("setting_form", "接入网线", None))
        self.cheakb_NAenabled.setText(_translate("setting_form", "启用", None))
        self.label_16.setText(_translate("setting_form", "引导顺序:", None))
        self.btn_up.setText(_translate("setting_form", "上移", None))
        self.btn_down.setText(_translate("setting_form", "下移", None))
        self.btn_confirm.setText(_translate("setting_form", "确定", None))
        self.btn_cancel.setText(_translate("setting_form", "取消", None))

