# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vcenter_Form.ui'
#
# Created: Sat Mar 07 16:44:18 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Vcenter_form(object):
    def setupUi(self, Vcenter_form):
        Vcenter_form.setObjectName(_fromUtf8("Vcenter_form"))
        Vcenter_form.resize(1041, 666)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Vcenter_form.sizePolicy().hasHeightForWidth())
        Vcenter_form.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(Vcenter_form)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(0, 30, 211, 591))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.treeView.setFont(font)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Aharoni"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 240, 421, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.widget_host = QtGui.QWidget(self.centralwidget)
        self.widget_host.setGeometry(QtCore.QRect(220, 30, 811, 591))
        self.widget_host.setObjectName(_fromUtf8("widget_host"))
        self.lab_hostname = QtGui.QLabel(self.widget_host)
        self.lab_hostname.setGeometry(QtCore.QRect(20, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.lab_hostname.setFont(font)
        self.lab_hostname.setObjectName(_fromUtf8("lab_hostname"))
        self.lab_IPAddr = QtGui.QLabel(self.widget_host)
        self.lab_IPAddr.setGeometry(QtCore.QRect(20, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.lab_IPAddr.setFont(font)
        self.lab_IPAddr.setObjectName(_fromUtf8("lab_IPAddr"))
        self.lab_hostver = QtGui.QLabel(self.widget_host)
        self.lab_hostver.setGeometry(QtCore.QRect(20, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.lab_hostver.setFont(font)
        self.lab_hostver.setObjectName(_fromUtf8("lab_hostver"))
        self.label_6 = QtGui.QLabel(self.widget_host)
        self.label_6.setGeometry(QtCore.QRect(330, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lab_cpuinfo = QtGui.QLabel(self.widget_host)
        self.lab_cpuinfo.setGeometry(QtCore.QRect(410, 170, 311, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_cpuinfo.setFont(font)
        self.lab_cpuinfo.setObjectName(_fromUtf8("lab_cpuinfo"))
        self.label_3 = QtGui.QLabel(self.widget_host)
        self.label_3.setGeometry(QtCore.QRect(330, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lab_cpucount = QtGui.QLabel(self.widget_host)
        self.lab_cpucount.setGeometry(QtCore.QRect(410, 230, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_cpucount.setFont(font)
        self.lab_cpucount.setObjectName(_fromUtf8("lab_cpucount"))
        self.label_4 = QtGui.QLabel(self.widget_host)
        self.label_4.setGeometry(QtCore.QRect(330, 290, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lab_memsize = QtGui.QLabel(self.widget_host)
        self.lab_memsize.setGeometry(QtCore.QRect(410, 290, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_memsize.setFont(font)
        self.lab_memsize.setObjectName(_fromUtf8("lab_memsize"))
        self.label_7 = QtGui.QLabel(self.widget_host)
        self.label_7.setGeometry(QtCore.QRect(330, 350, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pgbar_cpuusage = QtGui.QProgressBar(self.widget_host)
        self.pgbar_cpuusage.setGeometry(QtCore.QRect(410, 350, 251, 23))
        self.pgbar_cpuusage.setProperty("value", 24)
        self.pgbar_cpuusage.setObjectName(_fromUtf8("pgbar_cpuusage"))
        self.label_5 = QtGui.QLabel(self.widget_host)
        self.label_5.setGeometry(QtCore.QRect(330, 410, 81, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pgbar_memusage = QtGui.QProgressBar(self.widget_host)
        self.pgbar_memusage.setGeometry(QtCore.QRect(410, 410, 251, 23))
        self.pgbar_memusage.setProperty("value", 24)
        self.pgbar_memusage.setObjectName(_fromUtf8("pgbar_memusage"))
        self.label_8 = QtGui.QLabel(self.widget_host)
        self.label_8.setGeometry(QtCore.QRect(330, 460, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pgbar_diskusage = QtGui.QProgressBar(self.widget_host)
        self.pgbar_diskusage.setGeometry(QtCore.QRect(410, 490, 251, 23))
        self.pgbar_diskusage.setProperty("value", 24)
        self.pgbar_diskusage.setObjectName(_fromUtf8("pgbar_diskusage"))
        self.label_9 = QtGui.QLabel(self.widget_host)
        self.label_9.setGeometry(QtCore.QRect(330, 530, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lab_totalsize = QtGui.QLabel(self.widget_host)
        self.lab_totalsize.setGeometry(QtCore.QRect(500, 530, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_totalsize.setFont(font)
        self.lab_totalsize.setObjectName(_fromUtf8("lab_totalsize"))
        self.widget_vm = QtGui.QWidget(self.centralwidget)
        self.widget_vm.setGeometry(QtCore.QRect(220, 30, 811, 591))
        self.widget_vm.setObjectName(_fromUtf8("widget_vm"))
        self.lab_vmname = QtGui.QLabel(self.widget_vm)
        self.lab_vmname.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lab_vmname.setFont(font)
        self.lab_vmname.setObjectName(_fromUtf8("lab_vmname"))
        self.lab_vmpowerstate = QtGui.QLabel(self.widget_vm)
        self.lab_vmpowerstate.setGeometry(QtCore.QRect(20, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.lab_vmpowerstate.setFont(font)
        self.lab_vmpowerstate.setObjectName(_fromUtf8("lab_vmpowerstate"))
        self.btn_vmpowerstate = QtGui.QPushButton(self.widget_vm)
        self.btn_vmpowerstate.setGeometry(QtCore.QRect(130, 80, 61, 31))
        self.btn_vmpowerstate.setObjectName(_fromUtf8("btn_vmpowerstate"))
        self.lab_vmosversion = QtGui.QLabel(self.widget_vm)
        self.lab_vmosversion.setGeometry(QtCore.QRect(20, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.lab_vmosversion.setFont(font)
        self.lab_vmosversion.setObjectName(_fromUtf8("lab_vmosversion"))
        self.tb_vmdescription = QtGui.QTextBrowser(self.widget_vm)
        self.tb_vmdescription.setGeometry(QtCore.QRect(20, 200, 231, 141))
        self.tb_vmdescription.setReadOnly(True)
        self.tb_vmdescription.setObjectName(_fromUtf8("tb_vmdescription"))
        self.label_10 = QtGui.QLabel(self.widget_vm)
        self.label_10.setGeometry(QtCore.QRect(20, 180, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.widget_vm)
        self.label_11.setGeometry(QtCore.QRect(330, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lab_vmcpucount = QtGui.QLabel(self.widget_vm)
        self.lab_vmcpucount.setGeometry(QtCore.QRect(390, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmcpucount.setFont(font)
        self.lab_vmcpucount.setObjectName(_fromUtf8("lab_vmcpucount"))
        self.label_13 = QtGui.QLabel(self.widget_vm)
        self.label_13.setGeometry(QtCore.QRect(510, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lab_cpuexecutioncap = QtGui.QLabel(self.widget_vm)
        self.lab_cpuexecutioncap.setGeometry(QtCore.QRect(570, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_cpuexecutioncap.setFont(font)
        self.lab_cpuexecutioncap.setObjectName(_fromUtf8("lab_cpuexecutioncap"))
        self.label_15 = QtGui.QLabel(self.widget_vm)
        self.label_15.setGeometry(QtCore.QRect(330, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lab_vmmemsize = QtGui.QLabel(self.widget_vm)
        self.lab_vmmemsize.setGeometry(QtCore.QRect(390, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmmemsize.setFont(font)
        self.lab_vmmemsize.setObjectName(_fromUtf8("lab_vmmemsize"))
        self.label_17 = QtGui.QLabel(self.widget_vm)
        self.label_17.setGeometry(QtCore.QRect(510, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lab_vmvmemsize = QtGui.QLabel(self.widget_vm)
        self.lab_vmvmemsize.setGeometry(QtCore.QRect(570, 170, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmvmemsize.setFont(font)
        self.lab_vmvmemsize.setObjectName(_fromUtf8("lab_vmvmemsize"))
        self.label_37 = QtGui.QLabel(self.widget_vm)
        self.label_37.setGeometry(QtCore.QRect(330, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.widget_vm)
        self.label_38.setGeometry(QtCore.QRect(330, 250, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.widget_vm)
        self.label_39.setGeometry(QtCore.QRect(330, 290, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.lab_vmSCname = QtGui.QLabel(self.widget_vm)
        self.lab_vmSCname.setGeometry(QtCore.QRect(420, 290, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmSCname.setFont(font)
        self.lab_vmSCname.setObjectName(_fromUtf8("lab_vmSCname"))
        self.lab_vmSCtype = QtGui.QLabel(self.widget_vm)
        self.lab_vmSCtype.setGeometry(QtCore.QRect(480, 290, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmSCtype.setFont(font)
        self.lab_vmSCtype.setObjectName(_fromUtf8("lab_vmSCtype"))
        self.lab_vmdiskname = QtGui.QLabel(self.widget_vm)
        self.lab_vmdiskname.setGeometry(QtCore.QRect(420, 320, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmdiskname.setFont(font)
        self.lab_vmdiskname.setObjectName(_fromUtf8("lab_vmdiskname"))
        self.lab_disksize = QtGui.QLabel(self.widget_vm)
        self.lab_disksize.setGeometry(QtCore.QRect(480, 320, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_disksize.setFont(font)
        self.lab_disksize.setObjectName(_fromUtf8("lab_disksize"))
        self.label_44 = QtGui.QLabel(self.widget_vm)
        self.label_44.setGeometry(QtCore.QRect(330, 320, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.lab_vmdvdname = QtGui.QLabel(self.widget_vm)
        self.lab_vmdvdname.setGeometry(QtCore.QRect(420, 350, 231, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmdvdname.setFont(font)
        self.lab_vmdvdname.setObjectName(_fromUtf8("lab_vmdvdname"))
        self.label_47 = QtGui.QLabel(self.widget_vm)
        self.label_47.setGeometry(QtCore.QRect(330, 350, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.widget_vm)
        self.label_48.setGeometry(QtCore.QRect(330, 390, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.lab_vmNA1name = QtGui.QLabel(self.widget_vm)
        self.lab_vmNA1name.setGeometry(QtCore.QRect(420, 390, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lab_vmNA1name.setFont(font)
        self.lab_vmNA1name.setObjectName(_fromUtf8("lab_vmNA1name"))
        self.pgbar_cpuusage_2 = QtGui.QProgressBar(self.widget_vm)
        self.pgbar_cpuusage_2.setGeometry(QtCore.QRect(420, 220, 271, 21))
        self.pgbar_cpuusage_2.setProperty("value", 24)
        self.pgbar_cpuusage_2.setObjectName(_fromUtf8("pgbar_cpuusage_2"))
        self.pgbar_memusage_2 = QtGui.QProgressBar(self.widget_vm)
        self.pgbar_memusage_2.setGeometry(QtCore.QRect(420, 250, 271, 21))
        self.pgbar_memusage_2.setProperty("value", 24)
        self.pgbar_memusage_2.setObjectName(_fromUtf8("pgbar_memusage_2"))
        Vcenter_form.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Vcenter_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        Vcenter_form.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Vcenter_form)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Vcenter_form.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(Vcenter_form)
        self.action.setObjectName(_fromUtf8("action"))
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Vcenter_form)
        QtCore.QMetaObject.connectSlotsByName(Vcenter_form)

    def retranslateUi(self, Vcenter_form):
        Vcenter_form.setWindowTitle(_translate("Vcenter_form", "VirtualBox虚拟机管理中心", None))
        self.label.setText(_translate("Vcenter_form", "服务端列表", None))
        self.label_2.setText(_translate("Vcenter_form", "尚未添加VirtualBox服务端", None))
        self.lab_hostname.setText(_translate("Vcenter_form", "HostName", None))
        self.lab_IPAddr.setText(_translate("Vcenter_form", "IPAddress", None))
        self.lab_hostver.setText(_translate("Vcenter_form", "Host OS_Version", None))
        self.label_6.setText(_translate("Vcenter_form", "CPU信息    :", None))
        self.lab_cpuinfo.setText(_translate("Vcenter_form", "CPU Information", None))
        self.label_3.setText(_translate("Vcenter_form", "CPU核心数 :", None))
        self.lab_cpucount.setText(_translate("Vcenter_form", "ProcessorCount", None))
        self.label_4.setText(_translate("Vcenter_form", "内存大小    :", None))
        self.lab_memsize.setText(_translate("Vcenter_form", "MemSize", None))
        self.label_7.setText(_translate("Vcenter_form", "CPU使用率 :", None))
        self.label_5.setText(_translate("Vcenter_form", "内存使用率 :", None))
        self.label_8.setText(_translate("Vcenter_form", "VirtualBox所在分区使用情况  :", None))
        self.label_9.setText(_translate("Vcenter_form", "VirtualBox相关文件总大小 :", None))
        self.lab_totalsize.setText(_translate("Vcenter_form", "TotalSize", None))
        self.lab_vmname.setText(_translate("Vcenter_form", "Vm_Name", None))
        self.lab_vmpowerstate.setText(_translate("Vcenter_form", "VM_powerstate", None))
        self.btn_vmpowerstate.setText(_translate("Vcenter_form", "启动", None))
        self.lab_vmosversion.setText(_translate("Vcenter_form", "VM_OSVersion", None))
        self.label_10.setText(_translate("Vcenter_form", "虚拟机描述 :", None))
        self.label_11.setText(_translate("Vcenter_form", "CPU分配:", None))
        self.lab_vmcpucount.setText(_translate("Vcenter_form", "CPUCount", None))
        self.label_13.setText(_translate("Vcenter_form", "CPU峰值:", None))
        self.lab_cpuexecutioncap.setText(_translate("Vcenter_form", "100%", None))
        self.label_15.setText(_translate("Vcenter_form", "内存分配:", None))
        self.lab_vmmemsize.setText(_translate("Vcenter_form", "memsize", None))
        self.label_17.setText(_translate("Vcenter_form", "显存分配:", None))
        self.lab_vmvmemsize.setText(_translate("Vcenter_form", "vmemsize", None))
        self.label_37.setText(_translate("Vcenter_form", "CPU使用率:", None))
        self.label_38.setText(_translate("Vcenter_form", "内存使用率:", None))
        self.label_39.setText(_translate("Vcenter_form", "储存控制器:", None))
        self.lab_vmSCname.setText(_translate("Vcenter_form", "SC_name", None))
        self.lab_vmSCtype.setText(_translate("Vcenter_form", "SC_type", None))
        self.lab_vmdiskname.setText(_translate("Vcenter_form", "diskname", None))
        self.lab_disksize.setText(_translate("Vcenter_form", "disksize", None))
        self.label_44.setText(_translate("Vcenter_form", "虚拟磁盘:", None))
        self.lab_vmdvdname.setText(_translate("Vcenter_form", "diskname", None))
        self.label_47.setText(_translate("Vcenter_form", "虚拟光驱:", None))
        self.label_48.setText(_translate("Vcenter_form", "网络适配器1:", None))
        self.lab_vmNA1name.setText(_translate("Vcenter_form", "NA_name", None))
        self.menu.setTitle(_translate("Vcenter_form", "菜单", None))
        self.action.setText(_translate("Vcenter_form", "添加服务端", None))

